---
title: "Chapter 3 Describing Variables"
output: 
   html_document:
    toc: yes
    toc_depth: 3
    css: ../style-article.css
params:
  date: !r Sys.Date()    
---

```{r,setup, include=FALSE, eval=TRUE}
options(knitr.table.format = "html", width = 140)
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, fig.width = 12, fig.height = 8)
```

<div>Author: Rick Dean</div>
<div>Article date: `r params$date`</div>

<div class="abstract">
  <p class="abstract">Abstract</p>
    Notes and graphics from the book [The Effect-An Introduction to Research Design and Causality](https://theeffectbook.net/introduction.html) by Nick Huntington-klein.
</div>  

```{r, warning=FALSE, message=FALSE}
library(knitr)
library(kableExtra)
library(data.table)
library(RplotterPkg)
library(causaldata)
library(here)
```

## 3.3 The Distribution

Continuous Variables

```{r}

data("scorecard",package = "causaldata")

scorecard_dt <- data.table::setDT(scorecard)

RplotterPkg::create_histogram_plot(
  df = scorecard_dt,
  aes_x = "earnings_med",
  title = "Median Earnings of College Graduates",
  subtitle = "Source: scorecard 2007"
)
```
